### ISSUE TITLE
ServerNotify

### ISSUE THREAD

**Issue by kfn** [blackberry/BES10-Cascades#9]
In the method sendAlert() I think the header is wrong:
 HttpWReq.Headers.Add("ContentType", "text/plain");

I think it should be
 HttpWReq.Headers.Add("Content-Type", "text/plain");

I get an error on my bb device when receiving a push message:
Missing Content-type header for push

EDIT. I receive an error after changing ContentType to Content-Type:
Error: System.ArgumentException: The 'Content-Type' header must be modified using the appropriate property or method.
Parameter name: name
   at System.Net.WebHeaderCollection.ThrowOnRestrictedHeader(String headerName)
   at System.Net.WebHeaderCollection.Add(String name, String value)

**Comment by jmutter** [comment]
kfn, Thanks for the catch.  After looking at it, perhaps the best way is to simply use the ContentType property of the HttpWebRequest class.

HttpWReq.ContentType = "text/plain";
